
  CREATE TABLE "SCOTT"."USERINFO" 
   (	"USER_ID" NUMBER(5,0), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"PASSWORD_" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DISPLAY_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"COUNTRY" VARCHAR2(10 BYTE), 
	"JOB" VARCHAR2(20 BYTE), 
	"BIO" VARCHAR2(100 BYTE), 
	"CREATION_DATE" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE, 
	 UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
 

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011370" ON "SCOTT"."USERINFO" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
 
  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011371" ON "SCOTT"."USERINFO" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
 

  CREATE TABLE "SCOTT"."QUESTION" 
   (	"QUESTION_ID" NUMBER(38,0), 
	"TITLE" VARCHAR2(100 BYTE), 
	"QUESTION_TEXT" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"QUESTION_DATE_N_TIME" TIMESTAMP (2) DEFAULT systimestamp, 
	"USER_ID" NUMBER(5,0), 
	 PRIMARY KEY ("QUESTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE, 
	 FOREIGN KEY ("USER_ID")
	  REFERENCES "SCOTT"."USERINFO" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
 

  CREATE TABLE "SCOTT"."ANSWER" 
   (	"ANSWER_ID" NUMBER(10,0), 
	"ANSWER_TEXT" VARCHAR2(4000 BYTE), 
	"ANSWER_DATE" TIMESTAMP (6), 
	"USER_ID" NUMBER(5,0), 
	"QUESTION_ID" NUMBER(38,0), 
	 CONSTRAINT "ANSWER_PK" PRIMARY KEY ("ANSWER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ANSWER_USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "SCOTT"."USERINFO" ("USER_ID") ENABLE, 
	 CONSTRAINT "ANSWER_QUESTION_FK" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "SCOTT"."QUESTION" ("QUESTION_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE TABLE "SCOTT"."BADGE" 
   (	"BADGE_ID" NUMBER(10,0), 
	"BADGE_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"RANK" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"TYBE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(3000 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "B_ID" PRIMARY KEY ("BADGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE, 
	 UNIQUE ("BADGE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
 

  CREATE UNIQUE INDEX "SCOTT"."B_ID" ON "SCOTT"."BADGE" ("BADGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
 
  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011380" ON "SCOTT"."BADGE" ("BADGE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
 

  CREATE TABLE "SCOTT"."TAG" 
   (	"TAG_NAME" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("TAG_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
 

  CREATE TABLE "SCOTT"."VOTE" 
   (	"VOTE_ID" NUMBER(10,0), 
	"STATUS" VARCHAR2(15 BYTE), 
	"USER_ID" NUMBER(5,0), 
	"QUESTION_ID" NUMBER(10,0), 
	"ANSWER_ID" NUMBER(10,0), 
	 PRIMARY KEY ("VOTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE, 
	 CONSTRAINT "FK_USER_I_D" FOREIGN KEY ("USER_ID")
	  REFERENCES "SCOTT"."USERINFO" ("USER_ID") ENABLE, 
	 CONSTRAINT "FK_QUESTION_I_D" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "SCOTT"."QUESTION" ("QUESTION_ID") ENABLE, 
	 CONSTRAINT "FK_ANSWER_I_D" FOREIGN KEY ("ANSWER_ID")
	  REFERENCES "SCOTT"."ANSWER" ("ANSWER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
 

  CREATE TABLE "SCOTT"."PASSWORD_HISTORY" 
   (	"IP_ADDRESS" VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	"USER_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"STRING_" CHAR(64 BYTE) NOT NULL ENABLE, 
	"CREATION_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"VERFICATION_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"CREATION_TIME" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "PK_IP_ADDRESS" PRIMARY KEY ("IP_ADDRESS", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE, 
	 UNIQUE ("IP_ADDRESS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE, 
	 UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE, 
	 UNIQUE ("VERFICATION_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE, 
	 CONSTRAINT "FK_USER_ID" FOREIGN KEY ("USER_ID")
	  REFERENCES "SCOTT"."USERINFO" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
 

  CREATE UNIQUE INDEX "SCOTT"."PK_IP_ADDRESS" ON "SCOTT"."PASSWORD_HISTORY" ("IP_ADDRESS", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
 
  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011391" ON "SCOTT"."PASSWORD_HISTORY" ("IP_ADDRESS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
 
  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011392" ON "SCOTT"."PASSWORD_HISTORY" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
 
  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011393" ON "SCOTT"."PASSWORD_HISTORY" ("VERFICATION_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
 

  CREATE TABLE "SCOTT"."ACHIEVES" 
   (	"BADGE_ID" NUMBER(10,0), 
	"USER_ID" NUMBER(5,0), 
	 CONSTRAINT "FK_BADGE_ID" FOREIGN KEY ("BADGE_ID")
	  REFERENCES "SCOTT"."BADGE" ("BADGE_ID") ENABLE, 
	 CONSTRAINT "F_K_USER_ID" FOREIGN KEY ("USER_ID")
	  REFERENCES "SCOTT"."USERINFO" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
 

  CREATE TABLE "SCOTT"."HAS_1" 
   (	"TAG_NAME" VARCHAR2(45 BYTE), 
	"QUESTION_ID" NUMBER(5,0) NOT NULL ENABLE, 
	 UNIQUE ("QUESTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE, 
	 CONSTRAINT "FK_TAG_NAME" FOREIGN KEY ("TAG_NAME")
	  REFERENCES "SCOTT"."TAG" ("TAG_NAME") ENABLE, 
	 CONSTRAINT "F_K_QUESTION_ID" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "SCOTT"."QUESTION" ("QUESTION_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
 

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011404" ON "SCOTT"."HAS_1" ("QUESTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
 

  CREATE TABLE "SCOTT"."HAS_2" 
   (	"USER_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"ANSWER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"QUESTION_ID" NUMBER(5,0) NOT NULL ENABLE, 
	 UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX"  ENABLE, 
	 UNIQUE ("ANSWER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX"  ENABLE, 
	 UNIQUE ("QUESTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX"  ENABLE, 
	 CONSTRAINT "FK_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "SCOTT"."USERINFO" ("USER_ID") ENABLE, 
	 CONSTRAINT "FK_ANSWER" FOREIGN KEY ("ANSWER_ID")
	  REFERENCES "SCOTT"."ANSWER" ("ANSWER_ID") ENABLE, 
	 CONSTRAINT "FK_QUESTION" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "SCOTT"."QUESTION" ("QUESTION_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
 

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011656" ON "SCOTT"."HAS_2" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
 
  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011657" ON "SCOTT"."HAS_2" ("ANSWER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
 
  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011658" ON "SCOTT"."HAS_2" ("QUESTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
 
